"""Extracts each face style generated by PixelLab (sty_{cat}_{style}_{0=A,1=B}.png) into a game layer.
A pixel belongs to the layer when it changed vs the faceless head (v2_noface), lies inside the head,
is not plain skin, and its nearest facial anchor belongs to that category.
Game formats (same as the standing sprites):
  eyes  -> iris red-marker (tinted with eyeColor), brows green-marker (eyebrowColor), lashes/whites kept
  nose  -> grayscale, tinted with skinColor
  mouth -> real colours (untinted)"""
import math, os
from PIL import Image
from strip_face import lum
from clean_heads import components

OUT = os.path.dirname(os.path.abspath(__file__))
HEAD = {"A": ((98, 24), 20), "B": ((31, 75), 20)}
ANCHORS = {
    "A": {"eyes": [(90, 20), (101.5, 27.5)], "nose": [(92.5, 27)], "mouth": [(89.5, 31.5)]},
    "B": {"eyes": [(30, 68), (40, 78)], "nose": [(38, 70.5)], "mouth": [(41.5, 66.5)]},
}
# face "up" (toward the forehead): opposite of eyes-midpoint -> mouth
def up_dir(v):
    a = ANCHORS[v]; ex = sum(p[0] for p in a["eyes"]) / 2; ey = sum(p[1] for p in a["eyes"]) / 2
    mx, my = a["mouth"][0]; d = math.hypot(ex - mx, ey - my)
    return ((ex - mx) / d, (ey - my) / d)

def nearest_cat(v, x, y):
    best = None
    for cat, pts in ANCHORS[v].items():
        for px_, py_ in pts:
            d = math.hypot(x - px_, y - py_)
            if cat == "nose": d *= 1.4          # nose is tiny: only claim what is really close
            if not best or d < best[0]: best = (d, cat)
    return best

def is_skin(p, ref):
    r, g, b, a = p
    return r > g > b and r - b > 20 and ref * 0.75 <= lum(p) <= ref * 1.2

def extract(cat, style, v):
    i = 0 if v == "A" else 1
    path = f"{OUT}/sty_{cat}_{style}_{i}.png"
    if v == "B" and os.path.exists(f"{OUT}/styB_{cat}_{style}_0.png"):
        path = f"{OUT}/styB_{cat}_{style}_0.png"          # dedicated, clearer view-B generation
    gen = Image.open(path).convert("RGBA"); gp = gen.load()
    base = Image.open(f"{OUT}/{v}_v2_noface.png").convert("RGBA"); bp = base.load()
    (cx, cy), r = HEAD[v]
    vals = sorted(lum(bp[x, y]) for y in range(96) for x in range(128)
                  if bp[x, y][3] and (x - cx) ** 2 + (y - cy) ** 2 <= (r - 4) ** 2)
    ref = vals[len(vals) // 2]
    pts = []
    for y in range(96):
        for x in range(128):
            g = gp[x, y]
            if not g[3] or not bp[x, y][3] or (x - cx) ** 2 + (y - cy) ** 2 > (r - 2) ** 2:
                continue
            if sum(abs(g[k] - bp[x, y][k]) for k in range(3)) <= 30 or is_skin(g, ref):
                continue
            d, c = nearest_cat(v, x, y)
            if c == cat and d <= {"eyes": 7.5, "nose": 4, "mouth": 6}[cat]:
                pts.append((x, y))
    keep = [p for comp in components(pts) if len(comp) >= 3 for p in comp]
    out = Image.new("RGBA", (128, 96)); op = out.load()
    ux, uy = up_dir(v)
    for x, y in keep:
        p = gp[x, y]; L = lum(p)
        if cat == "eyes":
            # distance along the face "up" axis from the nearest eye centre -> brows sit above
            e = min(ANCHORS[v]["eyes"], key=lambda q: math.hypot(x - q[0], y - q[1]))
            above = (x - e[0]) * ux + (y - e[1]) * uy
            sat = max(p[:3]) - min(p[:3])
            if above > 2.5 and L < 110:
                v_ = max(60, min(255, round(255 - L)))            # brow -> green marker
                op[x, y] = (0, v_, 0, 255)
            elif style != "closedeyes" and sat > 40 and p[1] > p[0] and L > 35:
                v_ = max(80, min(255, round(L * 1.6)))           # iris -> red marker
                op[x, y] = (v_, 0, 0, 255)
            elif style == "closedeyes" and p[1] > p[0]:
                continue                                         # closed eyes: no iris colour at all
            else:
                op[x, y] = p                                     # lashes, outline, sclera, highlight
        elif cat == "nose":
            v_ = max(0, min(255, round(L / ref * 200)))
            op[x, y] = (v_, v_, v_, 255)
        else:
            op[x, y] = p
    return out

if __name__ == "__main__":
    os.makedirs(f"{OUT}/layers_v2/face", exist_ok=True)
    for cat, styles in (("eyes", ["cateyes", "relax", "closedeyes"]), ("mouth", ["catmouth", "smile", "biglips", "smirk"]),
                        ("nose", ["standard", "small"])):
        for st in styles:
            for v in "AB":
                extract(cat, st, v).save(f"{OUT}/layers_v2/face/{st}_lie{v}.png")
    print("ok")
