"""Per-body lying clothes: jacket/jeans generated by PixelLab on each final body (fit/*.png) are
aligned to that body, isolated, then fitted:
  1. holes inside the garment (skin seams between legs, missed pixels) are filled;
  2. the 1px rim of skin/body outline peeking along the garment edge is covered (never the head).
Writes layers_final/{tops,bottoms}/{jacket,jeans}_{male,female}_lie{A,B}.png (160x128, grayscale)."""
import os
from PIL import Image
from build_layers import to_raw, CLOTH_LUM
from make_female import best_shift

OUT = os.path.dirname(os.path.abspath(__file__))
DST = os.path.join(OUT, "layers_final")
PAD = 16
HEAD = {"A": ((98, 24), 21), "B": ((31, 75), 21)}
BODIES = {("male", "A"): "A_v2_noface.png", ("female", "A"): "A_female_noface.png",
          ("male", "B"): "B_v2_noface.png", ("female", "B"): "B_female_noface.png"}
GEN = {  # (garment, body, view) -> PixelLab output
    ("jacket", "male", "A"): "fit/jacketA_sleeve_0.png", ("jacket", "female", "A"): "fit/jacketA_sleeve_1.png",
    ("jacket", "male", "B"): "fit/jacket_2.png", ("jacket", "female", "B"): "fit/jacket_3.png",
    ("jeans", "male", "A"): "fit/jeans_0.png", ("jeans", "female", "A"): "fit/jeans_1.png",
    ("jeans", "male", "B"): "fit/jeans_2.png", ("jeans", "female", "B"): "fit/jeans_3.png",
}
N4 = ((1, 0), (-1, 0), (0, 1), (0, -1))

def lum(p): return 0.299 * p[0] + 0.587 * p[1] + 0.114 * p[2]

def shifted(im, dx, dy):
    out = Image.new("RGBA", im.size); out.alpha_composite(im, (-dx, -dy)); return out

def components(pts):
    pts, out = set(pts), []
    while pts:
        st = [pts.pop()]; comp = list(st)
        while st:
            x, y = st.pop()
            for dx, dy in N4:
                q = (x + dx, y + dy)
                if q in pts: pts.remove(q); st.append(q); comp.append(q)
        out.append(comp)
    return out

def fit(gen, base, head):
    (cx, cy), r = head
    gp, bp = gen.load(), base.load(); W, H = base.size
    in_head = lambda x, y, rr=r: (x - cx) ** 2 + (y - cy) ** 2 <= rr * rr
    def skin(p):
        return p[0] > p[1] > p[2] and p[0] - p[2] > 25 and lum(p) > 90
    def changed(x, y):
        g, b = gp[x, y], bp[x, y]
        return g[3] and (not b[3] or sum((g[i] - b[i]) ** 2 for i in range(3)) ** 0.5 > 35)
    core = {(x, y) for y in range(H) for x in range(W)
            if changed(x, y) and not skin(gp[x, y]) and 22 <= lum(gp[x, y]) <= 200 and not in_head(x, y)}
    # grow into the garment's own dark outline
    stack = list(core)
    while stack:
        x, y = stack.pop()
        for dx, dy in N4:
            q = (x + dx, y + dy)
            if 0 <= q[0] < W and 0 <= q[1] < H and q not in core and changed(*q) and lum(gp[q]) < 22 and not in_head(*q):
                core.add(q); stack.append(q)
    core = {p for c in components(core) if len(c) >= 6 for p in c}
    out = Image.new("RGBA", base.size); op = out.load()
    for p in core: op[p] = gp[p]

    def fill_from_neighbours(cells):
        cells = set(cells)
        while cells:
            done = {}
            for x, y in cells:
                nb = [op[x + dx, y + dy] for dx, dy in N4 + ((1, 1), (-1, -1), (1, -1), (-1, 1))
                      if 0 <= x + dx < W and 0 <= y + dy < H and op[x + dx, y + dy][3] and (x + dx, y + dy) not in cells]
                if nb:
                    done[(x, y)] = min(nb, key=lum)  # prefer the darker neighbour: keeps outlines crisp
            if not done: break
            for p, c in done.items(): op[p] = c
            cells -= done.keys()

    # 1. holes: body pixels enclosed by garment on opposite sides (horizontal or vertical, <=2px gap)
    holes = []
    for y in range(H):
        for x in range(W):
            if op[x, y][3] or not bp[x, y][3] or in_head(x, y, r + 2): continue
            for dx, dy in ((1, 0), (0, 1), (1, 1), (1, -1)):
                a = any(0 <= x - k * dx < W and 0 <= y - k * dy < H and op[x - k * dx, y - k * dy][3] for k in (1, 2))
                b = any(0 <= x + k * dx < W and 0 <= y + k * dy < H and op[x + k * dx, y + k * dy][3] for k in (1, 2))
                if a and b: holes.append((x, y)); break
    fill_from_neighbours(holes)
    # 2. rim: body pixels touching the garment that sit on the body's edge (outline/skin sliver)
    def body_edge(x, y):
        return any(not (0 <= x + dx < W and 0 <= y + dy < H) or not bp[x + dx, y + dy][3] for dx, dy in N4)
    rim = [(x, y) for y in range(H) for x in range(W)
           if bp[x, y][3] and not op[x, y][3] and not in_head(x, y, r + 2) and body_edge(x, y)
           and any(0 <= x + dx < W and 0 <= y + dy < H and op[x + dx, y + dy][3] for dx, dy in N4)]
    fill_from_neighbours(rim)
    return out

def pad(im):
    c = Image.new("RGBA", (128 + 2 * PAD, 96 + 2 * PAD)); c.alpha_composite(im, (PAD, PAD)); return c

def run():
    for (garment, body, v), gen_f in GEN.items():
        base = Image.open(os.path.join(OUT, BODIES[(body, v)])).convert("RGBA")
        gen = Image.open(os.path.join(OUT, gen_f)).convert("RGBA")
        iou, dx, dy = best_shift(base, gen)
        layer = fit(shifted(gen, dx, dy), base, HEAD[v])
        cat = "tops" if garment == "jacket" else "bottoms"
        os.makedirs(f"{DST}/{cat}", exist_ok=True)
        pad(to_raw(layer, CLOTH_LUM)).save(f"{DST}/{cat}/{garment}_{body}_lie{v}.png")
        print(garment, body, v, "shift", (dx, dy), "iou", round(iou, 3))
    # generic (body-agnostic) fallbacks = the male fit
    import shutil
    for v in "AB":
        shutil.copy(f"{DST}/tops/jacket_male_lie{v}.png", f"{DST}/tops/jacket_lie{v}.png")
        shutil.copy(f"{DST}/bottoms/jeans_male_lie{v}.png", f"{DST}/bottoms/jeans_lie{v}.png")

if __name__ == "__main__":
    run()
