name: frontend
description: Cozy Slow Dating Client Flutter Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  flame: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/furniture/
    - assets/images/wallpaper/
    - assets/images/floors/
    - assets/images/avatar/body/
    - assets/images/avatar/face_shape/
    - assets/images/avatar/eyes/
    - assets/images/avatar/eyebrows/
    - assets/images/avatar/mouth/
    - assets/images/avatar/nose/
    - assets/images/avatar/face_details/
    - assets/images/avatar/hair/
    - assets/images/avatar/tops/
    - assets/images/avatar/bottoms/
    - assets/images/avatar/shoes/
    - assets/images/avatar/accessories/
    - assets/images/avatar/64x128/body/
    - assets/images/avatar/64x128/face_shape/
    - assets/images/avatar/64x128/eyes/
    - assets/images/avatar/64x128/eyebrows/
    - assets/images/avatar/64x128/mouth/
    - assets/images/avatar/64x128/nose/
    - assets/images/avatar/64x128/face_details/
    - assets/images/avatar/64x128/hair/
    - assets/images/avatar/64x128/tops/
    - assets/images/avatar/64x128/bottoms/
    - assets/images/avatar/64x128/shoes/
    - assets/images/avatar/64x128/accessories/
    - assets/images/avatar/32x64/body/
    - assets/images/avatar/32x64/face_shape/
    - assets/images/avatar/32x64/eyes/
    - assets/images/avatar/32x64/eyebrows/
    - assets/images/avatar/32x64/mouth/
    - assets/images/avatar/32x64/nose/
    - assets/images/avatar/32x64/face_details/
    - assets/images/avatar/32x64/hair/
    - assets/images/avatar/32x64/tops/
    - assets/images/avatar/32x64/bottoms/
    - assets/images/avatar/32x64/shoes/
    - assets/images/avatar/32x64/accessories/
